trigger:
  batch: true
  branches:
    include:
    - '*'
  paths:
    include:
    - tests/*

pool:
  vmImage: 'ubuntu-latest'

variables:
  - template: variables/development.yml
  - name: buildPlatform
    value: 'Any CPU'
  - name: buildConfiguration
    value: 'Release'

stages:
  - stage: pull_request
    condition: or(eq(variables['Build.Reason'], 'PullRequest'),  startsWith(variables['Build.SourceBranch'], 'refs/pull'))
    variables:
      - template: variables/development.yml
      
    jobs:
      - job: test_src
        steps:
          - template: steps/src-test-steps.yml
            parameters:
              rgEnvironment: '$(rgEnvironment)'              
              unitPath: '$(srcPath)'
              unitProject: "*.Tests.csproj"
