variables:
  - group: ppn-rg-www-prod
  - template: common.yml
  - name: rgEnvironment
    value: 'Production'
  - name: rgName
    value: 'ppn-rg-www-prod-120'
  - name: rgLocation
    value: 'southafricanorth'
  - name: 'appiName'
    value: 'appi-www-prod-120'
  - name: 'kvName'
    value: 'kv-www-prod-120'
  - name: planName
    value: 'plan-www-prod-120'
  - name: planSku
    value: 'F1'
  - name: stName
    value: 'stwwwprod120'
  - name: webName
    value: 'web-www-prod-120'
  - name: workName
    value: 'work-www-prod-120'